application: enter_your_application_identifier_here
version: 1
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "10m"

handlers:
- url: /
  static_files: index.html
  upload: index\.html
  expiration: "0s"

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /browserconfig\.xml
  static_files: browserconfig.xml
  upload: browserconfig\.xml
- url: /manifest\.json
  static_files: manifest.json
  upload: manifest\.json
  mime_type: application/manifest+json

- url: /img
  static_dir: img
- url: /favicon\.ico
  static_files: img/favicon.ico
  upload: img/favicon\.ico
- url: /apple-touch-icon(?:-precomposed)?\.png
  static_files: img/ios-180.png
  upload: img/ios-180.png
- url: /apple-touch-icon-([0-9]+)x[0-9]+(?:-precomposed)?\.png
  static_files: img/ios-\1.png
  upload: img/ios-[0-9]+\.png

- url: /timetable\.appcache
  static_files: timetable.appcache
  upload: timetable\.appcache
  mime_type: text/cache-manifest
  expiration: "0s"

- url: /([-a-z0-9]+)
  static_files: timetables/\1.html
  upload: timetables/.*
  expiration: "0s"
- url: /([-a-zA-Z0-9]+)
  script: tolowercase.application
